#!/bin/bash
# 
# 
# Example:
#     alma-sky-coverage Coverage_Map_S2COSMOS/Coverage_Polygon_S2COSMOS_interpol.txt
# 

if [[ $(type almacosmos_sky_coverage.py 2>/dev/null | wc -l) -eq 0 ]]; then
    source $(dirname "${BASH_SOURCE[0]}")/SETUP.bash
fi

almacosmos_sky_coverage.py "$@"


