#!/bin/bash
# 


# 
# Check input argument
# 
if [[ $# -eq 0 ]]; then
    echo "Usage: "
    echo "    a3cosmos-ALMA-image-print-meta-table input_fits_directory [output_file_name]"
    echo "Input: "
    echo "    A directory containing the A3COSMOS fits images."
    echo "    For example, a \"fits/\" directory which contains:"
    echo "    \"*_SB*_GB*_MB*.spw*.cont.I.image.fits\""
    echo "Output: "
    echo "    If the second argument is given, then an ASCII table named \"output_file_name\" will be written."
    echo ""
    exit
fi


# 
# Call Python Script
# 
$(dirname ${BASH_SOURCE[0]})/$(basename ${BASH_SOURCE[0]}).py $@


