#!/bin/bash
# 

set -e



# 
# Check input argument
# 
if [[ $# -eq 0 ]]; then
    echo "Usage: "
    echo "    a3cosmos-MC-simulation-statistics-analysis \"datatable_CrossMatched_only_matches_filtered_nonphysical.fits\""
    echo "Input: "
    echo "    A catalog which contains \"S_in\", \"S_out\", \"flag_matched\", \"flag_nonmatched_missed\" columns"
    echo "Output: "
    echo "    A directory named \"Statistics/\""
    echo ""
    exit
fi


# 
# Check supermongo and necessary files
# 
if [[ $(type sm 2>/dev/null | wc -l) -eq 0 ]]; then
    echo "Error! Supermongo was not installed!"
    exit 1
fi
if [[ $(echo "load astroSfig.sm" | sm 2>&1 | wc -l) -ne 0 ]]; then
    echo "Error! Necessary Supermongo macros was not installed! Please download \"https://github.com/1054/DeepFields.SuperDeblending/Softwares/Supermongo_macro/*\" or contact liudz1054@gmail.com!"
    exit 1
fi
if [[ ! -d $(dirname "${BASH_SOURCE[0]}")/a3cosmos-MC-simulation-statistics-analysis-tools ]]; then
    echo "Error! \""$(dirname "${BASH_SOURCE[0]}")/a3cosmos-MC-simulation-statistics-analysis-tools"\" was not found! Please make sure you have completely downloaded \"https://github.com/1054/AlmaCosmos.git\"!"
    exit 1
fi
if [[ $(type a3cosmos-MC-simulation-make-plots-for-cross-matched-catalog 2>/dev/null | wc -l) -eq 0 ]]; then
    if [[ -f $(dirname "${BASH_SOURCE[0]}")/SETUP.bash ]]; then
        source $(dirname "${BASH_SOURCE[0]}")/SETUP.bash
    else
        echo "Error! \""$(dirname "${BASH_SOURCE[0]}")/SETUP.bash"\" was not found! Please make sure you have completely downloaded \"https://github.com/1054/AlmaCosmos.git\"!"
        exit 1
    fi
fi


# 
# Read Input cat
# 
InputCat="$1"


# 
# Set Output dir
# 
if [[ $# -ge 2 ]]; then
    OutputDir="$2"
else
    OutputDir="Statistics"
fi


# 
# Check output dir
# 
if [[ ! -d "$OutputDir" ]]; then
    mkdir -p "$OutputDir"
fi


# 
# Extract formatted data table
# 
if [[ "$InputCat" == *".fits" ]] || [[ "$InputCat" == *".FITS" ]]; then
    InputFmt="fits"
else
    InputFmt="ascii"
fi
if [[ ! -f "$OutputDir/simu_data_input.txt" ]]; then
    topcat -stilts tpipe \
                in="$InputCat" \
                ifmt="$InputFmt" \
                cmd="select \"S_peak/noise>=3.0\"" \
                cmd="keepcols \"ID S_in S_out e_S_out S_peak S_res noise Maj_in Min_in PA_in Maj_out Min_out PA_out Maj_beam Min_beam PA_beam image_file_STR simu_name_STR\"" \
                ofmt=ascii \
                out="$OutputDir/simu_data_input.txt"
fi
if [[ ! -f "$OutputDir/simu_data_input.txt" ]]; then
    echo "Error! Failed to output \"$OutputDir/simu_data_input.txt\"!"
    exit 1
fi


# 
# Change dir to OutputDir
# 
cd "$OutputDir"



# 
# Check analysis tools from 'a3cosmos-MC-simulation-statistics-analysis-tools'
# 
ScriptDir="$(dirname ${BASH_SOURCE[0]})/a3cosmos-MC-simulation-statistics-analysis-tools"
ScriptCheck="OK"
for ScriptName in "almacosmos_calc_simu_stats.py" \
                  "almacosmos_fit_simu_corr_ecorr_via_2D_function.py" \
                  "almacosmos_fit_simu_corr_ecorr_via_2D_interpolation.py" \
                  "almacosmos_fit_simu_corr_ecorr_via_function.py" \
                  "almacosmos_fit_simu_corr_ecorr_via_spline.py" \
                  "almacosmos_fit_simu_corr_fbias_via_2D_function.py" \
                  "almacosmos_fit_simu_corr_fbias_via_2D_interpolation.py" \
                  "almacosmos_fit_simu_corr_fbias_via_function.py" \
                  "almacosmos_fit_simu_corr_fbias_via_spline.py" \
                  "almacosmos_plot_simu_corr.py"
do
    if [[ ! -f "$ScriptDir/$ScriptName" ]]; then
        echo "Error! \"$ScriptDir/$ScriptName\" was not found! Please clone the entire \"https://github.com/1054/AlmaCosmos.git\"!"
        ScriptCheck="ERROR"
    fi
done
if [[ "$ScriptCheck" != "OK" ]]; then
    exit 255
fi








# 
# Before first step, we make some quality check plots
# 
if [[ ! -d "Statistics_quick_plots_0" ]]; then
a3cosmos-MC-simulation-make-plots-for-cross-matched-catalog "simu_data_input.txt" -out "Statistics_quick_plots_0"
fi







# 
# The first step is to make bins in the parameter space and compute (S_in-S_out) statistics in each bin.
# For doing this, we use the code "almacosmos_calc_simu_stats.py".
# 
if [[ ! -f "sim_diagram_output_no_galfit_flux_error_1/datatable_param_grid_cell_statistics.txt" ]]; then
"$ScriptDir/almacosmos_calc_simu_stats.py" "simu_data_input.txt" -out "sim_diagram_output_no_galfit_flux_error_1" | tee "log_calc_simu_stats_1.log"
fi
cd "sim_diagram_output_no_galfit_flux_error_1"
# 
# Then, we run
#   "almacosmos_fit_simu_corr_fbias.py" to fit a 2D function to the flux bias.
#   "almacosmos_fit_simu_corr_fbias_via_2D_interpolation.py" to interpolate the flux bias.
#   "almacosmos_fit_simu_corr_fbias_via_spline.py" to spline the flux bias.
#   "almacosmos_fit_simu_corr_fbias_via_function.py" to fit 1D function to the flux bias.
# 
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_2D_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_2D_interpolation.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_spline.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_2D_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_2D_interpolation.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_spline.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_function.py"
"$ScriptDir/almacosmos_plot_simu_corr.py"
# 
# After fitted the flux bias correction functions, we apply the correction to the input data "simu_data_input.txt"
# 
"$ScriptDir/almacosmos_apply_simu_corr_fbias_via_spline_table.py" "../simu_data_input.txt"
"$ScriptDir/almacosmos_plot_corrected_fbias.sh"
cd ..
#else
#echo ""; echo "Found existing \"sim_diagram_output_no_galfit_flux_error_1\"! Skip the first step fbias correction!"; echo ""; 
#fi
a3cosmos-MC-simulation-make-plots-for-cross-matched-catalog "simu_data_input_corrected.txt" -out "Statistics_quick_plots_1"







# 
# Repeat for ecorr
# 
if [[ ! -f "sim_diagram_output_no_galfit_flux_error_2/datatable_param_grid_cell_statistics.txt" ]]; then
"$ScriptDir/almacosmos_calc_simu_stats.py" "simu_data_input_corrected.txt" -out "sim_diagram_output_no_galfit_flux_error_2" | tee "log_calc_simu_stats_2.log"
fi
cd "sim_diagram_output_no_galfit_flux_error_2"
# 
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_2D_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_2D_interpolation.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_spline.py"
"$ScriptDir/almacosmos_fit_simu_corr_fbias_via_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_2D_function.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_2D_interpolation.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_spline.py"
"$ScriptDir/almacosmos_fit_simu_corr_ecorr_via_function.py"
"$ScriptDir/almacosmos_plot_simu_corr.py"
# 
"$ScriptDir/almacosmos_apply_simu_corr_ecorr_via_fitfun_table.py" "../simu_data_input_corrected.txt"
"$ScriptDir/almacosmos_plot_corrected_ecorr.sh"
mkdir "Plot_corrected_ecorr__via_fitfun_table"
mv "Plot_corrected_ecorr"*.* "Plot_uncorrected_ecorr"*.* "Plot_corrected_ecorr__via_fitfun_table/"
mv "datatable_applied_correction_ecorr.txt" "Plot_corrected_ecorr__via_fitfun_table/"
#mv "datatable_applying_correction_ecorr.txt" "Plot_corrected_ecorr__via_fitfun_table/"
mv "datatable_applied_correction_ecorr_with_more_columns.txt" "Plot_corrected_ecorr__via_fitfun_table/"
mv "../simu_data_input_corrected_corrected.txt" "../simu_data_input_corrected_corrected__via_fitfun_table.txt"
# 
"$ScriptDir/almacosmos_apply_simu_corr_ecorr_via_spline_table.py" "../simu_data_input_corrected.txt"
"$ScriptDir/almacosmos_plot_corrected_ecorr.sh"
mkdir "Plot_corrected_ecorr__via_spline_table"
mv "Plot_corrected_ecorr"*.* "Plot_uncorrected_ecorr"*.* "Plot_corrected_ecorr__via_spline_table/"
mv "datatable_applied_correction_ecorr.txt" "Plot_corrected_ecorr__via_spline_table/"
#mv "datatable_applying_correction_ecorr.txt" "Plot_corrected_ecorr__via_spline_table/"
mv "datatable_applied_correction_ecorr_with_more_columns.txt" "Plot_corrected_ecorr__via_spline_table/"
mv "../simu_data_input_corrected_corrected.txt" "../simu_data_input_corrected_corrected__via_spline_table.txt"
# 
cd ..
#else
#echo ""; echo "Found existing \"sim_diagram_output_no_galfit_flux_error_2\"! Skip the second step ecorr correction!"; echo ""; 
#fi
a3cosmos-MC-simulation-make-plots-for-cross-matched-catalog "simu_data_input_corrected_corrected__via_spline_table.txt" -out "Statistics_quick_plots_2"













# 
# Make plots
# 
#a3cosmos-MC-simulation-make-plots-for-cross-matched-catalog simu_data_input_corrected.txt















# 
# Print final message
# 
echo "************"
echo "Output to \"$OutputDir\"!"


