#!/bin/bash
# 

if [[ $(type topcat | wc -l) -eq 0 ]]; then
    echo "Error! Topcat was not found!"
    exit
fi

# Usage
if [[ $# -lt 1 ]]; then
    echo "Usage: "
    echo "  This code will combine the input catalog and the meta table."
    echo "  To run this code, please input the catalog file path and the meta table file path:"
    echo "  e.g., $(basename ${BASH_SOURCE[0]}) cat_pybdsm_concatenated_141117.fits '/Volumes/GoogleDrive/Team Drives/A3COSMOS/Data/ALMA_full_archive/Calibrated_Images_by_Benjamin/v20170604/fits_meta_table_for_dataset_v20170604_with_pbeam.fits'"
    echo ""
    echo "  Note that the meta table should be a txt file, and the first row should be #-commented header line, and the second row the data."
    echo ""
    exit
fi


if [[ "$1" != *".fits" ]]; then
    echo "Error! The input \"$1\" is not a *.fits file!"
    exit 255
fi
if [[ "$2" == *".fits" ]]; then
    meta_table_fmt="fits"
    meta_table_file="$2"
    meta_table_name=$(basename "$2" | sed -e 's/\.fits$//g')
elif [[ "$2" == *".txt" ]]; then
    meta_table_fmt="ascii"
    meta_table_file="$2"
    meta_table_name=$(basename "$2" | sed -e 's/\.txt$//g')
else
    echo "Error! The input \"$2\" is not a *.txt nor a *.fits file!"
    exit 255
fi


if [[ ! -f "$1" ]] && [[ ! -L "$1" ]]; then
    echo "Error! The input \"$1\" does not exist!"
    exit 255
fi
if [[ ! -f "$2" ]] && [[ ! -L "$2" ]]; then
    echo "Error! The input \"$2\" does not exist!"
    exit 255
fi


cat_input=$(echo "$1" | sed -e 's/\.fits$//g')


# 
# reformat meta table, so that there are no extra commented line between the header line and the first data line
# 
if [[ "$meta_table_fmt" == "ascii" ]]; then
    N_data_line=2
    while [[ $(cat "${meta_table_file}" | head -n $N_data_line | tail -n 1 | grep "^#" | wc -l) -eq 1 ]]; do
        N_data_line=$((N_data_line+1))
    done
    cat "${meta_table_file}" | awk "(NR==1||NR>=$N_data_line) {print}" > "${meta_table_name}_reformatted_for_topcat.txt"
    meta_table_file="${meta_table_name}_reformatted_for_topcat.txt"
fi


topcat -stilts tmatchn \
                nin=2 \
                in1="${cat_input}.fits" \
                values1="Image" \
                suffix1="_PyBDSM" \
                in2="${meta_table_file}" \
                ifmt2="${meta_table_fmt}" \
                icmd2="replacecol image_file -name \"image_file_meta_table\" \"image_file\"" \
                values2="image_file_meta_table" \
                suffix2="" \
                matcher=exact \
                multimode=pairs \
                fixcols=dups \
                iref=1 \
                join1=always \
                ocmd="delcols \"image_file_meta_table\"" \
                out="${cat_input}_with_meta.fits"
                # http://www.star.bristol.ac.uk/~mbt/stilts/sun256/tmatchn-usage.html




